### ISSUE TITLE
Potential issue with "extended mode" keys in keyboard handling code

### ISSUE THREAD

**Issue by jm--** [seL4/libplatsupport#2]
I believe I found an error in the keyboard handling code in libplatsupport. In particular, it seems "extended mode" keys such as cursor keys are not processed correctly.

Function `keyboard_state_push_ps2_keyevent()` has a ` int16_t ps2_keyevent` parameter and contains the following code:

    /* Prepend 0xE0 to ps2 keycode if in extended mode. */
    if (s->state & KEYBOARD_PS2_STATE_EXTENDED_MODE) {
        ps2_keyevent = 0xE000 + (ps2_keyevent & 0xFF);
        s->state &= ~KEYBOARD_PS2_STATE_EXTENDED_MODE;
    }

    int16_t vkey = keycode_ps2_to_vkey(ps2_keyevent);

When an extended mode key is processed, the value of variable `ps2_keyevent` becomes negative because the sign bit is set after adding 0xE000.

Function `keycode_ps2_to_vkey()`, which accepts `ps2_keycode` as a parameter of type int32_t, is called immediately afterwards.

Now here is the problem: Because of sign extension, the negative value of `ps2_keycode` is retained 
inside `keycode_ps2_to_vkey()`, which leads to the `switch` statement there not finding a match.

My current fix is to replace in `keyboard_state_push_ps2_keyevent()`
```
    int16_t vkey = keycode_ps2_to_vkey(ps2_keyevent);
```
with
```
    int16_t vkey = keycode_ps2_to_vkey((uint16_t)ps2_keyevent);
```

I'm hacking on some example programs, and the fix is working for me.

**Comment by AdrianDanis** [comment]
Is there any reason `ps2_keycode` should be signed to begin with? It looks like it is being created from a `uint8_t` and then cast to the `int16_t`, but it feels like the variable should just be `uint16_t` to begin with. Does this seem reasonable?

**Comment by jm--** [comment]
I dismissed that option initially because the function contains this if-statement:
```
    if (ps2_keyevent <= -1) {
        return ev_none;
    }
```
But you are right! Given the current state of the source code, `ps2_keyevent` can never be negative.

Taking out the if-statement and changing  `ps2_keyevent` from `int16_t` to `uint16_t` might be the cleanest solution. What do you think?

**Comment by AdrianDanis** [comment]
Sounds good to me
